### ISSUE TITLE
There are examples of it

### ISSUE THREAD

**Issue by hz453673181** [yandex-load/JMeter-xmpp-plugin#1]
There are examples of it

**Comment by nnugumanov** [comment]
Examples of what?
Please, could you write more explicitly what the problem you have encountered with?

**Comment by hz453673181** [comment]
We have a mobile communications software，server using openfire
With this plug-in can impersonate a client to another client message

**Comment by VartikaRai** [comment]
Its not working .Seems issue in jar.

Please go through the logs and suggest way forward.

2014/11/21 11:00:05 INFO  - jmeter.util.JMeterUtils: Setting Locale to en_US 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: Loading user properties from: D:\Shared Folder\apache-jmeter-2.7\apache-jmeter-2.7\bin\user.properties 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: Loading system properties from: D:\Shared Folder\apache-jmeter-2.7\apache-jmeter-2.7\bin\system.properties 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: Copyright (c) 1998-2012 The Apache Software Foundation 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: Version 2.7 r1342410 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: java.version=1.7.0_45 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: java.vm.name=Java HotSpot(TM) Client VM 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: os.name=Windows 7 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: os.arch=x86 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: os.version=6.1 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: file.encoding=Cp1252 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: Default Locale=English (United States) 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: JMeter  Locale=English (United States) 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: JMeterHome=D:\Shared Folder\apache-jmeter-2.7\apache-jmeter-2.7 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: user.dir  =D:\Shared Folder\apache-jmeter-2.7\apache-jmeter-2.7\bin 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: PWD       =D:\Shared Folder\apache-jmeter-2.7\apache-jmeter-2.7\bin 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: IP: 10.203.28.171 Name: GURWIF6331 FullName: GURWIF6331.ad.aricent.com 
2014/11/21 11:00:05 INFO  - jmeter.JMeter: Loaded icon properties from org/apache/jmeter/images/icon.properties 
2014/11/21 11:00:05 INFO  - jmeter.engine.util.CompoundVariable: Note: Function class names must contain the string: '.functions.' 
2014/11/21 11:00:05 INFO  - jmeter.engine.util.CompoundVariable: Note: Function class names must not contain the string: '.gui.' 
2014/11/21 11:00:05 INFO  - jmeter.gui.action.LookAndFeelCommand: Using look and feel: javax.swing.plaf.metal.MetalLookAndFeel [Metal, CrossPlatform] 
2014/11/21 11:00:06 INFO  - jmeter.util.BSFTestElement: Registering JMeter version of JavaScript engine as work-round for BSF-22 
2014/11/21 11:00:06 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Cannot find .className property for htmlParser, using default 
2014/11/21 11:00:06 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/html is  
2014/11/21 11:00:06 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for application/xhtml+xml is  
2014/11/21 11:00:06 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for application/xml is  
2014/11/21 11:00:06 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/xml is  
2014/11/21 11:00:06 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser 
2014/11/21 11:00:06 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Reuse SSL session context on subsequent iterations: true 
2014/11/21 11:00:06 INFO  - jmeter.gui.util.MenuFactory: Skipping org.apache.jmeter.protocol.http.modifier.gui.ParamModifierGui 
2014/11/21 11:00:06 INFO  - jmeter.samplers.SampleResult: Note: Sample TimeStamps are START times 
2014/11/21 11:00:06 INFO  - jmeter.samplers.SampleResult: sampleresult.default.encoding is set to ISO-8859-1 
2014/11/21 11:00:06 INFO  - jmeter.samplers.SampleResult: sampleresult.useNanoTime=true 
2014/11/21 11:00:06 INFO  - jmeter.samplers.SampleResult: sampleresult.nanoThreadSleep=5000 
2014/11/21 11:00:11 INFO  - jmeter.services.FileServer: Default base='D:\Shared Folder\apache-jmeter-2.7\apache-jmeter-2.7\bin' 
2014/11/21 11:00:11 INFO  - jmeter.gui.action.Load: Loading file: D:\Shared Folder\apache-jmeter-2.7\apache-jmeter-2.7\bin\BEEZZ..jmx 
2014/11/21 11:00:11 INFO  - jmeter.services.FileServer: Set new base='D:\Shared Folder\apache-jmeter-2.7\apache-jmeter-2.7\bin' 
2014/11/21 11:00:11 INFO  - jmeter.save.SaveService: Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2 
2014/11/21 11:00:11 INFO  - jmeter.save.SaveService: Using SaveService properties file encoding UTF-8 
2014/11/21 11:00:11 INFO  - jmeter.save.SaveService: Using SaveService properties file version 1332608 
2014/11/21 11:00:11 INFO  - jmeter.save.SaveService: Using SaveService properties version 2.3 
2014/11/21 11:00:11 INFO  - jmeter.save.SaveService: All converter versions present and correct 
2014/11/21 11:00:12 INFO  - jmeter.services.FileServer: Set new base='D:\Shared Folder\apache-jmeter-2.7\apache-jmeter-2.7\bin' 
2014/11/21 11:00:13 INFO  - jmeter.engine.StandardJMeterEngine: Listeners will be started after enabling running version 
2014/11/21 11:00:13 INFO  - jmeter.engine.StandardJMeterEngine: To revert to the earlier behaviour, define jmeterengine.startlistenerslater=false 
2014/11/21 11:00:13 INFO  - jmeter.engine.StandardJMeterEngine: Running the test! 
2014/11/21 11:00:13 INFO  - jmeter.gui.util.JMeterMenuBar: setRunning(true,_local_) 
2014/11/21 11:00:13 INFO  - jmeter.engine.StandardJMeterEngine: Starting 1 threads for group p2p -file send/recieve. 
2014/11/21 11:00:13 INFO  - jmeter.engine.StandardJMeterEngine: Thread will continue on error 
2014/11/21 11:00:13 INFO  - jmeter.threads.JMeterThread: jmeterthread.startearlier=true (see jmeter.properties) 
2014/11/21 11:00:13 INFO  - jmeter.threads.JMeterThread: Running PostProcessors in forward order 
2014/11/21 11:00:13 INFO  - jmeter.engine.StandardJMeterEngine: All threads have been started 
2014/11/21 11:00:13 INFO  - jmeter.threads.JMeterThread: Thread started: p2p -file send/recieve 1-1 
2014/11/21 11:00:13 ERROR - ru.yandex.jmeter.XMPPClientImpl: Error reading data java.lang.RuntimeException: Retries more than 1000, aborting read
                at ru.yandex.jmeter.XMPPClientImpl.read(XMPPClientImpl.java:116)
                at org.apache.jmeter.protocol.tcp.sampler.TCPSampler.sample(TCPSampler.java:360)
                at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:442)
                at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:271)
                at java.lang.Thread.run(Thread.java:744)

2014/11/21 11:00:13 ERROR - jmeter.protocol.tcp.sampler.TCPSampler:  java.lang.RuntimeException: Error reading data
                at ru.yandex.jmeter.XMPPClientImpl.read(XMPPClientImpl.java:152)
                at org.apache.jmeter.protocol.tcp.sampler.TCPSampler.sample(TCPSampler.java:360)
                at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:442)
                at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:271)
                at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.RuntimeException: Retries more than 1000, aborting read
                at ru.yandex.jmeter.XMPPClientImpl.read(XMPPClientImpl.java:116)
                ... 4 more

2014/11/21 11:00:13 INFO  - jmeter.threads.JMeterThread: Thread finished: p2p -file send/recieve 1-1 
2014/11/21 11:00:13 INFO  - jmeter.engine.StandardJMeterEngine: Ending thread p2p -file send/recieve 1-1 
2014/11/21 11:00:13 INFO  - jmeter.engine.StandardJMeterEngine: Notifying test listeners of end of test 
2014/11/21 11:00:13 INFO  - jmeter.gui.util.JMeterMenuBar: setRunning(false,_local_) 
2014/11/21 11:00:13 INFO  - jmeter.engine.StandardJMeterEngine: Test has ended on host null

I have read jave script 126 line which is not inline
