### ISSUE TITLE
Error setting a test

### ISSUE THREAD

**Issue by artefactop** [yandex-load/JMeter-xmpp-plugin#2]
Hello,
I'm trying to set up a simple test for:
- Connect
- Authorization
- Bind Resource
- Set Session
- Send Initial Presence
- Send Message
- Close Connection

Looks like is unavailable to read the response from server side in seconds and subsequents calls, in first call I see the response in View Result Tree.

This is my template http://pastebin.com/KGhUfuZY

I'm getting this error from Jmeter log:

```
2015/04/24 15:56:05 INFO  - jmeter.engine.StandardJMeterEngine: Running the test! 
2015/04/24 15:56:05 INFO  - jmeter.samplers.SampleEvent: List of sample_variables: [] 
2015/04/24 15:56:05 INFO  - jmeter.gui.util.JMeterMenuBar: setRunning(true,*local*) 
2015/04/24 15:56:05 INFO  - jmeter.engine.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group 
2015/04/24 15:56:05 INFO  - jmeter.engine.StandardJMeterEngine: Starting 1 threads for group Thread Group. 
2015/04/24 15:56:05 INFO  - jmeter.engine.StandardJMeterEngine: Thread will continue on error 
2015/04/24 15:56:05 INFO  - jmeter.threads.ThreadGroup: Starting thread group number 1 threads 1 ramp-up 1 perThread 1000.0 delayedStart=false 
2015/04/24 15:56:05 INFO  - jmeter.threads.ThreadGroup: Started thread group number 1 
2015/04/24 15:56:05 INFO  - jmeter.engine.StandardJMeterEngine: All thread groups have been started 
2015/04/24 15:56:05 INFO  - jmeter.threads.JMeterThread: Thread started: Thread Group 1-1 
2015/04/24 15:57:05 ERROR - ru.yandex.jmeter.XMPPClientImpl: Error reading data java.lang.RuntimeException: Retries more than 1000, aborting read
    at ru.yandex.jmeter.XMPPClientImpl.read(XMPPClientImpl.java:116)
    at org.apache.jmeter.protocol.tcp.sampler.TCPSampler.sample(TCPSampler.java:414)
    at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
    at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
    at java.lang.Thread.run(Thread.java:695)

2015/04/24 15:57:05 ERROR - jmeter.protocol.tcp.sampler.TCPSampler:  java.lang.RuntimeException: Error reading data
    at ru.yandex.jmeter.XMPPClientImpl.read(XMPPClientImpl.java:152)
    at org.apache.jmeter.protocol.tcp.sampler.TCPSampler.sample(TCPSampler.java:414)
    at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
    at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
    at java.lang.Thread.run(Thread.java:695)
Caused by: java.lang.RuntimeException: Retries more than 1000, aborting read
    at ru.yandex.jmeter.XMPPClientImpl.read(XMPPClientImpl.java:116)
    ... 4 more
```

What could be wrong?

**Comment by undera** [comment]
Hey! BTW you can use http://jmeter-plugins.org/wiki/XMPPSet/ , it's easier to set up.
